---
title: "2. Demanda Escolar"
author: "GPF"
date: '2022-06-11'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Packages
```{r}
library(tidyverse)
library(kableExtra)
library(readxl)
```

# Bases

## 2018
```{r}
a1_18 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2018/A1_Oferta_Establecimientos_etapa_regular_2018_Admision_2019.csv")

b1_18 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2018/B1_Postulantes_etapa_regular_2018_Admision_2019_PUBL.csv")

c1_18 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2018/C1_Postulaciones_etapa_regular_2018_Admision_2019_PUBL.csv")

d1_18 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2018/D1_Resultados_etapa_regular_2018_Admision_2019_PUBL.csv")
```

## 2019
```{r}
a1_19 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2019/A1_Oferta_Establecimientos_etapa_regular_2019_Admision_2020.csv")

b1_19 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2019/B1_Postulantes_etapa_regular_2019_Admision_2020_PUBL.csv")

c1_19 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2019/C1_Postulaciones_etapa_regular_2019_Admision_2020_PUBL.csv")

d1_19 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2019/D1_Resultados_etapa_regular_2019_Admision_2020_PUBL.csv")
```

## 2020
```{r}
a1_20 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2020/A1_Oferta_Establecimientos_etapa_regular_2020_Admision_2021.csv")

b1_20 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2020/B1_Postulantes_etapa_regular_2020_Admision_2021_PUBL.csv")

c1_20 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2020/C1_Postulaciones_etapa_regular_2020_Admision_2021_PUBL.csv")

d1_20 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2020/D1_Resultados_etapa_regular_2020_Admision_2021_PUBL.csv")
```

## 2021
```{r}
a1_21 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2021/A1_Oferta_Establecimientos_etapa_regular_2021_Admision_2022.csv")

b1_21 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2021/B1_Postulantes_etapa_regular_2021_Admision_2022_PUBL.csv")

c1_21 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2021/C1_Postulaciones_etapa_regular_2021_Admision_2022_PUBL.csv")

d1_21 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/SAE/2021/D1_Resultados_etapa_regular_2021_Admision_2022_PUBL.csv")
```

# Manipulacion

## 2018

### Postulantes
```{r}
b1_18 <- left_join(b1_18, c1_18%>%
  group_by(mrun)%>%
  summarise(continuidad = sum(prioridad_matriculado)), by = 'mrun')

b1_18 <- b1_18%>%
  mutate(
    cod_nivel = ifelse(cod_nivel < 1, 0,
    ifelse(cod_nivel == 1,1,
    ifelse(cod_nivel > 1 & cod_nivel < 9,2,
    ifelse(cod_nivel == 9, 3, 4)))))
```

### Postulaciones
```{r}
c1_18 <- data.frame(c1_18%>%
  arrange(mrun, preferencia_postulante)%>%
  group_by(mrun, rbd)%>%
    mutate(pos_valida = ifelse(duplicated(mrun, rbd) == F, 1,0)))

c1_18 <- list(c1_18,
     
c1_18%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    demanda_cod_curso = n())%>%
  select(rbd, cod_curso, demanda_cod_curso)%>%
  filter(duplicated(rbd, cod_curso) == F),              
                       
c1_18%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    first_pref = sum(preferencia_postulante == 1))%>%
  select(rbd, cod_curso, first_pref)%>%
  filter(duplicated(rbd, cod_curso) == F),

c1_18%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    second_pref = sum(preferencia_postulante == 2))%>%
  select(rbd, cod_curso, second_pref)%>%
  filter(duplicated(rbd, cod_curso) == F),

c1_18%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    third_pref = sum(preferencia_postulante == 3))%>%
  select(rbd, cod_curso, third_pref)%>%
  filter(duplicated(rbd, cod_curso) == F)) %>%
  
  reduce(left_join, by = c('rbd', 'cod_curso'))

c1_18 <- data.frame(c1_18%>%
  group_by(mrun)%>%
  mutate(
    alguna_prio = ifelse(prioridad_matriculado == 1 | prioridad_hermano == 1 | prioridad_hijo_funcionario == 1 | prioridad_exalumno == 1, 1,0),
    alguna_prio = max(alguna_prio),
    prio_colegio_origen = max(prioridad_matriculado),
    prio_fam = ifelse(prioridad_hermano == 1 | prioridad_hijo_funcionario == 1, 1,0),
    prio_fam = max(prio_fam)))
```

### Oferta
```{r}
#caso unico para rbd 2018
a1_18 <- a1_18%>%
  mutate(
    unico = duplicated(a1_18$rbd),
    unico = ifelse(unico == FALSE, 1, 0))

mat18 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/Resumen de matrícula por establecimiento/Resumen-matricula-EE-2018/Resumen_Matricula_EE_Oficial_2018.csv")

mat18 <- mat18%>%
  mutate(
    region = ifelse(NOM_COM_RBD == 'BULNES'|
NOM_COM_RBD == 'CHILLAN'|
NOM_COM_RBD == 'CHILLAN VIEJO'|
NOM_COM_RBD == 'COBQUECURA'|
NOM_COM_RBD == 'COELEMU'|
NOM_COM_RBD == 'COIHUECO'|
NOM_COM_RBD == 'EL CARMEN'|
NOM_COM_RBD == 'NINHUE'|
NOM_COM_RBD == 'ÑIQUEN'|
NOM_COM_RBD == 'PEMUCO'|
NOM_COM_RBD == 'PINTO'|
NOM_COM_RBD == 'PORTEZUELO'|
NOM_COM_RBD == 'QUILLON'|
NOM_COM_RBD == 'QUIRIHUE'|
NOM_COM_RBD == 'RANQUIL'|
NOM_COM_RBD == 'SAN CARLOS'|
NOM_COM_RBD == 'SAN FABIAN'|
NOM_COM_RBD == 'SAN IGNACIO'|
NOM_COM_RBD == 'SAN NICOLAS'|
NOM_COM_RBD == 'TREHUACO'|
NOM_COM_RBD == 'YUNGAY', 16, COD_REG_RBD))

a1_18 <- left_join(a1_18, mat18 %>%
  select(RBD, COD_DEPE2, RURAL_RBD, region, MAT_TOTAL)%>%
  rename(rbd = RBD, dep = COD_DEPE2, zona = RURAL_RBD, mat_total = MAT_TOTAL), by = 'rbd')

a1_18 <- a1_18 %>%
  mutate(dep = ifelse(dep == 1 | dep == 5, 0,1))

a1_18 <- a1_18%>%
  mutate(
    macro = ifelse(region == 15 | region == 1| region == 2 | region == 3, 0,
                  ifelse(region == 4 | region == 5, 1,
                  ifelse(region == 6 | region == 7 | region == 8 |region == 16, 2,
                  ifelse(region == 9 | region == 10 | region == 14, 3,
                  ifelse(region == 11 | region == 12, 4, 5))))))

# macro
#0 = norte
#1 = centro
#2 = centro sur
#3 = sur
#4 = austral
#5 = metropolitana

dir18 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/1. Datos Abiertos MINEDUC/Directorio Establecimientos/Directorio-oficial-EE-2018/Directorio_Oficial_EE_2018.csv")

a1_18 <- left_join(a1_18, dir18%>%
  select(RBD, PAGO_MATRICULA, PAGO_MENSUAL)%>%
    rename(rbd = RBD), by = 'rbd')

a1_18 <- a1_18%>%
  mutate(PAGO_MATRICULA = ifelse(PAGO_MATRICULA == '$1.000 A $10.000' | PAGO_MATRICULA == '$10.001 A $25.000', 1,
        ifelse(PAGO_MATRICULA == '$25.001 A $50.000' | PAGO_MATRICULA == '$50.001 A $100.000', 2,
        ifelse(PAGO_MATRICULA == 'MAS DE $100.000', 3,
        ifelse(PAGO_MATRICULA == 'GRATUITO', 0, NA)))))

a1_18 <- a1_18%>%
  mutate(PAGO_MENSUAL = ifelse(PAGO_MENSUAL == '$1.000 A $10.000' | PAGO_MENSUAL == '$10.001 A $25.000', 1,
    ifelse(PAGO_MENSUAL == '$25.001 A $50.000' | PAGO_MENSUAL == '$50.001 A $100.000', 2,
    ifelse(PAGO_MENSUAL == 'MAS DE $100.000', 3, 
    ifelse(PAGO_MENSUAL == 'GRATUITO', 0, NA)))))

sep18 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/1. Datos Abiertos MINEDUC/Alumnos SEP por rbd (MINEDUC)/SEP-2018/Preferentes_Prioritarios_y_Beneficiarios_SEP_2018.csv")

a1_18 <- left_join(a1_18, sep18%>%
  select(RBD, N_PRIO)%>%
  rename(rbd = RBD), by = 'rbd')

a1_18 <- a1_18%>%
  mutate(
    N_PRIO = ifelse(is.na(N_PRIO) == T, 0, N_PRIO),
    prop_prio_mattotal = N_PRIO/mat_total,
    prop_prio_mattotal = ifelse(prop_prio_mattotal <= .25, 0,
                            ifelse(prop_prio_mattotal >= .2500001 & prop_prio_mattotal <= .5, 1,2)))

CDB2017 <- read_excel("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/2. Agencia de Calidad de la Educación/Categorías de desempeño/CDB2017.xlsx")

CDM2017 <- read_excel("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/2. Agencia de Calidad de la Educación/Categorías de desempeño/CDM2017.xlsx")

a1_18 <- data.frame(list(a1_18,
     CDB2017%>%
  select(RBD, `Categoría Desempeño 2017`)%>%
  rename(rbd = RBD, CDB_2017 = `Categoría Desempeño 2017`),
  CDM2017%>%
  select(RBD, `Categoría Desempeño 2017`)%>%
  rename(rbd = RBD, CDM_2017 = `Categoría Desempeño 2017`)
  )%>%
  reduce(left_join, by = c('rbd')))

a1_18 <- a1_18%>%
  mutate(
    CDB_2017 = ifelse(CDB_2017 == 'ALTO', 3,
                      ifelse(CDB_2017 == 'INSUFICIENTE', 0,
                             ifelse(CDB_2017 == 'MEDIO', 2,
                                    ifelse(CDB_2017 == 'MEDIO-BAJO' | CDB_2017 == 'MEDIO-BAJO (NUEVO)', 1, NA)))),
    CDM_2017 = ifelse(CDM_2017 == 'ALTO', 3,
                      ifelse(CDM_2017 == 'INSUFICIENTE', 0,
                             ifelse(CDM_2017 == 'MEDIO', 2,
                                    ifelse(CDM_2017 == 'MEDIO-BAJO' | CDM_2017 == 'MEDIO-BAJO (NUEVO)', 1, NA)))))

#0 = insuficiente
#1 = medio bajo
#2 = medio
#3 = alto

a1_18 <- data.frame(a1_18%>%
  group_by(rbd)%>%
  mutate(
    CDB_2017 = ifelse(is.na(CDB_2017), -1, CDB_2017),
    CDM_2017 = ifelse(is.na(CDM_2017), -1, CDM_2017),
    CDG = max(CDB_2017, CDM_2017),
    CDG = ifelse(CDG == -1, NA, CDG)))

a1_18 <- a1_18%>%
  mutate(
    ciclo_educativo = ifelse(cod_nivel < 1, 0,
    ifelse(cod_nivel >= 1 & cod_nivel < 9,1,2)))

simce_4b_2017 <- read_excel("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/2. Agencia de Calidad de la Educación/SIMCE/2017/Simce4b2017_privada_SEG/Archivos XLS (XLSX)/simce4b2017_rbd_final.xlsx")

simce_8b_2017 <- read_excel("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/2. Agencia de Calidad de la Educación/SIMCE/2017/Simce8b2017_privada_SEG/Archivos XLS (XLSX)/simce8b2017_rbd_final.xlsx")

simce_2m_2017 <- read_excel("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/2. Agencia de Calidad de la Educación/SIMCE/2017/Simce2m2017_privada_SEG/Archivos XLS (XLSX)/simce2m2017_rbd_privada_final.xlsx")

a1_18 <-left_join(a1_18, simce_4b_2017%>%
  select(rbd, cod_grupo, palu_eda_ins_lect4b_rbd, palu_eda_ins_mate4b_rbd)%>%
  rename(gse4b = cod_grupo, ins_lec4b = palu_eda_ins_lect4b_rbd, ins_mat4b = palu_eda_ins_mate4b_rbd)%>%
    mutate(
      ins_lec4b = ifelse(ins_lec4b <= 20, 0,
      ifelse(ins_lec4b > 25 & ins_lec4b <= 40, 1, 2)),
      ins_mat4b = ifelse(ins_mat4b <= 20, 0,
      ifelse(ins_mat4b > 25 & ins_mat4b <= 40, 1, 2))), by = 'rbd')

a1_18 <-left_join(a1_18, simce_8b_2017%>%
  select(rbd, cod_grupo)%>%
  rename(gse8b = cod_grupo), by = 'rbd')

a1_18 <-left_join(a1_18, simce_2m_2017%>%
  select(rbd, cod_grupo, palu_eda_ins_lect2m_rbd, palu_eda_ins_mate2m_rbd)%>%
  rename(gse2m = cod_grupo, ins_lec2m = palu_eda_ins_lect2m_rbd, ins_mat2m = palu_eda_ins_mate2m_rbd)%>%
    mutate(
      ins_lec2m = ifelse(ins_lec2m <= 20, 0,
      ifelse(ins_lec2m > 25 & ins_lec2m <= 40, 1, 2)),
      ins_mat2m = ifelse(ins_mat2m <= 25, 0,
      ifelse(ins_mat2m > 25 & ins_mat2m <= 40, 1, 2))), by = 'rbd')

a1_18 <- data.frame(a1_18%>%
  mutate(
    ins_lec4b = ifelse(is.na(ins_lec4b) == T, -1, ins_lec4b),
    ins_lec2m = ifelse(is.na(ins_lec2m) == T, -1, ins_lec2m),
    ins_mat4b = ifelse(is.na(ins_mat4b) == T, -1, ins_mat4b),
    ins_mat2m = ifelse(is.na(ins_mat2m) == T, -1, ins_mat2m))%>%
  group_by(rbd)%>%
  mutate(
    ins_lec_rbd = max(ins_lec4b, ins_lec2m),
    ins_mat_rbd = max(ins_mat4b, ins_mat2m)))
  
a1_18 <- a1_18%>%
  mutate(
    gse8b = ifelse(gse8b == 'Bajo', 1,
    ifelse(gse8b == 'Medio bajo', 2,
    ifelse(gse8b == 'Medio', 3,
    ifelse(gse8b == 'Medio alto', 4,5)))),
    gse2m = ifelse(gse2m == 'Bajo', 1,
    ifelse(gse2m == 'Medio bajo', 2,
    ifelse(gse2m == 'Medio', 3,
    ifelse(gse2m == 'Medio alto', 4,5)))))

a1_18<- data.frame(a1_18%>%
  mutate(
    gse4b = ifelse(is.na(gse4b) == T, -1, gse4b),
    gse8b = ifelse(is.na(gse8b) == T, -1, gse8b),
    gse2m = ifelse(is.na(gse2m) == T, -1, gse2m))%>%
  group_by(rbd)%>%
  mutate(
    gse_rbd = max(gse4b, gse8b, gse2m)))

a1_18 <- left_join(a1_18, c1_18%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    demanda_cod_curso = n())%>%
  select(rbd, cod_curso, demanda_cod_curso)%>%
  filter(duplicated(rbd, cod_curso) == F))

a1_18 <- a1_18%>%
  mutate(demanda_cod_curso = ifelse(is.na(demanda_cod_curso) == T, 0, demanda_cod_curso))

a1_18 <- left_join(a1_18, c1_18%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    first_pref = sum(preferencia_postulante == 1))%>%
  select(rbd, cod_curso, first_pref)%>%
  filter(duplicated(rbd, cod_curso) == F), by = c('rbd', 'cod_curso'))

a1_18 <- a1_18%>%
  mutate(first_pref = ifelse(is.na(first_pref) == T, 0, first_pref))

a1_18 <- a1_18%>%
  mutate(
    col_ps_tipos = ifelse(dep == 0, 0,
              ifelse(dep == 1 & prop_prio_mattotal == 0, 1,
              ifelse(dep == 1 & prop_prio_mattotal == 1, 2,
              ifelse(dep == 1 & prop_prio_mattotal == 2, 3, NA)))))

remove(sep18, mat18, dir18, CDM2017, CDB2017, simce_4b_2017, simce_8b_2017, simce_2m_2017)
```

### Resultados
```{r}
d1_18 <- d1_18%>%
  mutate(rbd_admitido = ifelse(is.na(rbd_admitido) == T, -1, rbd_admitido))

d1_18 <- d1_18%>%
  mutate(rbd = ifelse(is.na(rbd_admitido_post_resp) == T, rbd_admitido, rbd_admitido_post_resp))

d1_18 <- left_join(d1_18, c1_18%>%
                     filter(pos_valida == 1)%>%
            select(mrun, rbd, preferencia_postulante, prioridad_matriculado, prioridad_matriculado:prioridad_exalumno, es_pie), by = c('mrun', 'rbd'))

d1_18 <- d1_18%>%
  mutate(cambia_colegio = ifelse(respuesta_postulante == 2 & rbd_admitido == rbd_admitido_post_resp, 0,
  ifelse(respuesta_postulante == 2 & rbd_admitido != rbd_admitido_post_resp, 1, NA)))

d1_18 <- left_join(d1_18, b1_18%>%
            select(mrun, continuidad), by = 'mrun')

d1_18 <- left_join(d1_18, c1_18%>%
                     filter(prioridad_matriculado==1)%>%
            select(mrun, rbd)%>%
              rename(rbd_origen = rbd), by = 'mrun')

d1_18 <- d1_18%>%
  mutate(rbd_admision = ifelse(continuidad==1, rbd_admitido, NA))

d1_18 <- left_join(d1_18, a1_18
          %>%filter(unico == 1)%>%
            select(rbd, con_copago, dep, zona, prop_prio_mattotal,CDG)%>%
            rename(rbd_origen = rbd, con_copago_or = con_copago, dep_or = dep, zona_or = zona, prop_prio_mattotal_or = prop_prio_mattotal, CDG_or = CDG), by = 'rbd_origen')


d1_18 <- left_join(d1_18, a1_18
          %>%filter(unico == 1)%>%
            select(rbd, con_copago, dep, zona, prop_prio_mattotal,CDG)%>%
            rename(rbd_admision = rbd, con_copago_ad = con_copago, dep_ad = dep, zona_ad = zona, prop_prio_mattotal_ad = prop_prio_mattotal,CDG_ad = CDG), by = 'rbd_admision')
```

## 2019

### Postulantes
```{r}
b1_19 <- left_join(b1_19, c1_19%>%
  group_by(mrun)%>%
  summarise(continuidad = sum(prioridad_matriculado)), by = 'mrun')

b1_19 <- b1_19%>%
  mutate(
    cod_nivel = ifelse(cod_nivel < 1, 0,
    ifelse(cod_nivel == 1,1,
    ifelse(cod_nivel > 1 & cod_nivel < 9,2,
    ifelse(cod_nivel == 9, 3, 4)))))
```

### Postulaciones
```{r}
c1_19 <- data.frame(c1_19%>%
  arrange(mrun, preferencia_postulante)%>%
  group_by(mrun, rbd)%>%
    mutate(pos_valida = ifelse(duplicated(mrun, rbd) == F, 1,0)))

c1_19 <- list(c1_19,
     
c1_19%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    demanda_cod_curso = n())%>%
  select(rbd, cod_curso, demanda_cod_curso)%>%
  filter(duplicated(rbd, cod_curso) == F),              
                       
c1_19%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    first_pref = sum(preferencia_postulante == 1))%>%
  select(rbd, cod_curso, first_pref)%>%
  filter(duplicated(rbd, cod_curso) == F),

c1_19%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    second_pref = sum(preferencia_postulante == 2))%>%
  select(rbd, cod_curso, second_pref)%>%
  filter(duplicated(rbd, cod_curso) == F),

c1_19%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    third_pref = sum(preferencia_postulante == 3))%>%
  select(rbd, cod_curso, third_pref)%>%
  filter(duplicated(rbd, cod_curso) == F)) %>%
  
  reduce(left_join, by = c('rbd', 'cod_curso'))

c1_19 <- data.frame(c1_19%>%
  group_by(mrun)%>%
  mutate(
    alguna_prio = ifelse(prioridad_matriculado == 1 | prioridad_hermano == 1 | prioridad_hijo_funcionario == 1 | prioridad_exalumno == 1, 1,0),
    alguna_prio = max(alguna_prio),
    prio_colegio_origen = max(prioridad_matriculado),
    prio_fam = ifelse(prioridad_hermano == 1 | prioridad_hijo_funcionario == 1, 1,0),
    prio_fam = max(prio_fam)))
```

### Oferta
```{r}
#caso unico para rbd 2018
a1_19 <- a1_19%>%
  mutate(
    unico = duplicated(a1_19$rbd),
    unico = ifelse(unico == FALSE, 1, 0))

mat19 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/Resumen de matrícula por establecimiento/Resumen-matricula-EE-2019/Resumen_Matricula_EE_Oficial_2019.csv")

a1_19 <- left_join(a1_19, mat19 %>%
  select(RBD, COD_DEPE2, RURAL_RBD, COD_REG_RBD, MAT_TOTAL)%>%
  rename(rbd = RBD, dep = COD_DEPE2, zona = RURAL_RBD, mat_total = MAT_TOTAL, region = COD_REG_RBD), by = 'rbd')

a1_19 <- a1_19 %>%
  mutate(dep = ifelse(dep == 1 | dep == 5, 0,1))

a1_19 <- a1_19%>%
  mutate(
    macro = ifelse(region == 15 | region == 1| region == 2 | region == 3, 0,
                  ifelse(region == 4 | region == 5, 1,
                  ifelse(region == 6 | region == 7 | region == 8 |region == 16, 2,
                  ifelse(region == 9 | region == 10 | region == 14, 3,
                  ifelse(region == 11 | region == 12, 4, 5))))))

dir19 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/1. Datos Abiertos MINEDUC/Directorio Establecimientos/Directorio-oficial-EE-2019/Directorio_Oficial_EE_2019.csv")

a1_19 <- left_join(a1_19, dir19%>%
  select(RBD, PAGO_MATRICULA, PAGO_MENSUAL)%>%
    rename(rbd = RBD), by = 'rbd')

a1_19 <- a1_19%>%
  mutate(PAGO_MATRICULA = ifelse(PAGO_MATRICULA == '$1.000 A $10.000' | PAGO_MATRICULA == '$10.001 A $25.000', 1,
        ifelse(PAGO_MATRICULA == '$25.001 A $50.000' | PAGO_MATRICULA == '$50.001 A $100.000', 2,
        ifelse(PAGO_MATRICULA == 'MAS DE $100.000', 3,
        ifelse(PAGO_MATRICULA == 'GRATUITO', 0, NA)))))

a1_19 <- a1_19%>%
  mutate(PAGO_MENSUAL = ifelse(PAGO_MENSUAL == '$1.000 A $10.000' | PAGO_MENSUAL == '$10.001 A $25.000', 1,
    ifelse(PAGO_MENSUAL == '$25.001 A $50.000' | PAGO_MENSUAL == '$50.001 A $100.000', 2,
    ifelse(PAGO_MENSUAL == 'MAS DE $100.000', 3, 
    ifelse(PAGO_MENSUAL == 'GRATUITO', 0, NA)))))

sep19 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/1. Datos Abiertos MINEDUC/Alumnos SEP por rbd (MINEDUC)/SEP-2019/Preferentes_Prioritarios_y_Beneficiarios_SEP_2019.csv")

a1_19 <- left_join(a1_19, sep19%>%
  select(RBD, N_PRIO)%>%
  rename(rbd = RBD), by = 'rbd')

a1_19 <- a1_19%>%
  mutate(
    N_PRIO = ifelse(is.na(N_PRIO) == T, 0, N_PRIO),
    prop_prio_mattotal = N_PRIO/mat_total,
    prop_prio_mattotal = ifelse(prop_prio_mattotal <= .25, 0,
                            ifelse(prop_prio_mattotal >= .2500001 & prop_prio_mattotal <= .5, 1,2)))

CDB2018 <- read_excel("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/2. Agencia de Calidad de la Educación/Categorías de desempeño/CDB2018.xlsx")

CDM2018 <- read_excel("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/2. Agencia de Calidad de la Educación/Categorías de desempeño/CDM2018.xlsx")

a1_19 <- data.frame(list(a1_19,
  CDB2018%>%
  select(RBD, `Categoría Desempeño 2018`)%>%
  rename(rbd = RBD, CDB_2018 = `Categoría Desempeño 2018`),
  
  CDM2018%>%
  select(RBD, `Categoría Desempeño 2018`)%>%
  rename(rbd = RBD, CDM_2018 = `Categoría Desempeño 2018`))%>%
  
    reduce(left_join, by = c('rbd')))

a1_19 <- a1_19%>%
  mutate(
    CDB_2018 = ifelse(CDB_2018 == 'ALTO', 3,
                      ifelse(CDB_2018 == 'INSUFICIENTE', 0,
                             ifelse(CDB_2018 == 'MEDIO', 2,
                                    ifelse(CDB_2018 == 'MEDIO-BAJO' | CDB_2018 == 'MEDIO-BAJO (NUEVO)', 1, NA)))),
    CDM_2018 = ifelse(CDM_2018 == 'ALTO', 3,
                      ifelse(CDM_2018 == 'INSUFICIENTE', 0,
                             ifelse(CDM_2018 == 'MEDIO', 2,
                                    ifelse(CDM_2018 == 'MEDIO-BAJO' | CDM_2018 == 'MEDIO-BAJO (NUEVO)', 1, NA)))))

a1_19 <- data.frame(a1_19%>%
  group_by(rbd)%>%
  mutate(
    CDB_2018 = ifelse(is.na(CDB_2018), -1, CDB_2018),
    CDM_2018 = ifelse(is.na(CDM_2018), -1, CDM_2018),
    CDG = max(CDB_2018, CDM_2018),
    CDG = ifelse(CDG == -1, NA, CDG)))

a1_19 <- a1_19%>%
  mutate(
    ciclo_educativo = ifelse(cod_nivel < 1, 0,
    ifelse(cod_nivel >= 1 & cod_nivel < 9,1,2)))

simce_4b_2018 <- read_excel("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/2. Agencia de Calidad de la Educación/SIMCE/2018/Simce4b_2018/Archivos XLS (XLSX)/simce4b2018_rbd_privada_final.xlsx")

simce_6b_2018 <- read_excel("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/2. Agencia de Calidad de la Educación/SIMCE/2018/Simce6b_2018/Archivos XLS (XLSX)/simce6b2018_rbd_privada_final.xlsx")

simce_2m_2018 <- read_excel("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/2. Agencia de Calidad de la Educación/SIMCE/2018/Simce2m_2018/Archivos XLS (XLSX)/simce2m2018_rbd_privada_final.xlsx")

a1_19 <-left_join(a1_19, simce_4b_2018%>%
  select(rbd, cod_grupo, palu_eda_ins_lect4b_rbd, palu_eda_ins_mate4b_rbd)%>%
  rename(gse4b = cod_grupo, ins_lec4b = palu_eda_ins_lect4b_rbd, ins_mat4b = palu_eda_ins_mate4b_rbd)%>%
    mutate(
      ins_lec4b = ifelse(ins_lec4b <= 20, 0,
      ifelse(ins_lec4b > 25 & ins_lec4b <= 40, 1, 2)),
      ins_mat4b = ifelse(ins_mat4b <= 20, 0,
      ifelse(ins_mat4b > 25 & ins_mat4b <= 40, 1, 2))), by = 'rbd')

a1_19 <-left_join(a1_19, simce_6b_2018%>%
  select(rbd, cod_grupo, palu_eda_ins_lect6b_rbd, palu_eda_ins_mate6b_rbd)%>%
  rename(gse6b = cod_grupo, ins_lec6b = palu_eda_ins_lect6b_rbd, ins_mat6b = palu_eda_ins_mate6b_rbd)%>%
    mutate(
      ins_lec6b = ifelse(ins_lec6b <= 20, 0,
      ifelse(ins_lec6b > 25 & ins_lec6b <= 40, 1, 2)),
      ins_mat6b = ifelse(ins_mat6b <= 20, 0,
      ifelse(ins_mat6b > 25 & ins_mat6b <= 40, 1, 2))), by = 'rbd')

a1_19 <-left_join(a1_19, simce_2m_2018%>%
  select(rbd, cod_grupo, palu_eda_ins_lect2m_rbd, palu_eda_ins_mate2m_rbd)%>%
  rename(gse2m = cod_grupo, ins_lec2m = palu_eda_ins_lect2m_rbd, ins_mat2m = palu_eda_ins_mate2m_rbd)%>%
    mutate(
      ins_lec2m = ifelse(ins_lec2m <= 20, 0,
      ifelse(ins_lec2m > 25 & ins_lec2m <= 40, 1, 2)),
      ins_mat2m = ifelse(ins_mat2m <= 20, 0,
      ifelse(ins_mat2m > 25 & ins_mat2m <= 40, 1, 2))), by = 'rbd')

a1_19 <- data.frame(a1_19%>%
  mutate(
    ins_lec4b = ifelse(is.na(ins_lec4b) == T, -1, ins_lec4b),
    ins_lec6b = ifelse(is.na(ins_lec6b) == T, -1, ins_lec6b),
    ins_lec2m = ifelse(is.na(ins_lec2m) == T, -1, ins_lec2m),
    ins_mat4b = ifelse(is.na(ins_mat4b) == T, -1, ins_mat4b),
    ins_mat6b = ifelse(is.na(ins_mat6b) == T, -1, ins_mat6b),
    ins_mat2m = ifelse(is.na(ins_mat2m) == T, -1, ins_mat2m))%>%
  group_by(rbd)%>%
  mutate(
    ins_lec_rbd = max(ins_lec4b, ins_lec6b, ins_lec2m),
    ins_mat_rbd = max(ins_mat4b, ins_mat6b, ins_mat2m)))

a1_19 <- data.frame(a1_19%>%
  mutate(
    gse4b = ifelse(is.na(gse4b) == T, -1, gse4b),
    gse6b = ifelse(is.na(gse6b) == T, -1, gse6b),
    gse2m = ifelse(is.na(gse2m) == T, -1, gse2m))%>%
  group_by(rbd)%>%
  mutate(
    gse_rbd = max(gse4b, gse6b, gse2m)))

a1_19 <- left_join(a1_19, c1_19%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    demanda_cod_curso = n())%>%
  select(rbd, cod_curso, demanda_cod_curso)%>%
  filter(duplicated(rbd, cod_curso) == F))

a1_19 <- a1_19%>%
  mutate(demanda_cod_curso = ifelse(is.na(demanda_cod_curso) == T, 0, demanda_cod_curso))

a1_19 <- left_join(a1_19, c1_19%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    first_pref = sum(preferencia_postulante == 1))%>%
  select(rbd, cod_curso, first_pref)%>%
  filter(duplicated(rbd, cod_curso) == F), by = c('rbd', 'cod_curso'))

a1_19 <- a1_19%>%
  mutate(first_pref = ifelse(is.na(first_pref) == T, 0, first_pref))

a1_19 <- a1_19%>%
  mutate(
    col_ps_tipos = ifelse(dep == 0, 0,
              ifelse(dep == 1 & prop_prio_mattotal == 0, 1,
              ifelse(dep == 1 & prop_prio_mattotal == 1, 2,
              ifelse(dep == 1 & prop_prio_mattotal == 2, 3, NA)))))

remove(sep19, mat19, dir19, CDM2018, CDB2018, simce_4b_2018, simce_6b_2018, simce_2m_2018)
```

### Resultados
```{r}
d1_19 <- d1_19%>%
  mutate(rbd_admitido = ifelse(is.na(rbd_admitido) == T, -1, rbd_admitido))

d1_19 <- d1_19%>%
  mutate(rbd = ifelse(is.na(rbd_admitido_post_resp) == T, rbd_admitido, rbd_admitido_post_resp))

d1_19 <- left_join(d1_19, c1_19%>%
                     filter(pos_valida == 1)%>%
            select(mrun, rbd, preferencia_postulante, prioridad_matriculado, prioridad_matriculado:prioridad_exalumno, es_pie), by = c('mrun', 'rbd'))

d1_19 <- d1_19%>%
  mutate(cambia_colegio = ifelse(respuesta_postulante == 2 & rbd_admitido == rbd_admitido_post_resp, 0,
  ifelse(respuesta_postulante == 2 & rbd_admitido != rbd_admitido_post_resp, 1, NA)))

d1_19 <- left_join(d1_19, b1_19%>%
            select(mrun, continuidad), by = 'mrun')

d1_19 <- left_join(d1_19, c1_19%>%
                     filter(prioridad_matriculado==1)%>%
            select(mrun, rbd)%>%
              rename(rbd_origen = rbd), by = 'mrun')

d1_19 <- d1_19%>%
  mutate(rbd_admision = ifelse(continuidad==1, rbd_admitido, NA))

d1_19 <- left_join(d1_19, a1_19%>%
                     filter(unico == 1)%>%
                     select(rbd, con_copago, dep, zona, prop_prio_mattotal,CDG)%>%
            rename(rbd_origen = rbd, con_copago_or = con_copago, dep_or = dep, zona_or = zona, prop_prio_mattotal_or = prop_prio_mattotal, CDG_or = CDG), by = 'rbd_origen')


d1_19 <- left_join(d1_19, a1_19%>%
                     filter(unico == 1)%>%
                     select(rbd, con_copago, dep, zona, prop_prio_mattotal,CDG)%>%
            rename(rbd_admision = rbd, con_copago_ad = con_copago, dep_ad = dep, zona_ad = zona, prop_prio_mattotal_ad = prop_prio_mattotal,CDG_ad = CDG), by = 'rbd_admision')
```

## 2020

### Postulantes
```{r}
b1_20 <- left_join(b1_20, c1_20%>%
  group_by(mrun)%>%
  summarise(continuidad = sum(prioridad_matriculado)), by = 'mrun')

b1_20 <- b1_20%>%
  mutate(
    cod_nivel = ifelse(cod_nivel < 1, 0,
    ifelse(cod_nivel == 1,1,
    ifelse(cod_nivel > 1 & cod_nivel < 9,2,
    ifelse(cod_nivel == 9, 3, 4)))))
```

### Postulaciones
```{r}
c1_20 <- data.frame(c1_20%>%
  arrange(mrun, preferencia_postulante)%>%
  group_by(mrun, rbd)%>%
    mutate(pos_valida = ifelse(duplicated(mrun, rbd) == F, 1,0)))

c1_20 <- list(c1_20,
     
c1_20%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    demanda_cod_curso = n())%>%
  select(rbd, cod_curso, demanda_cod_curso)%>%
  filter(duplicated(rbd, cod_curso) == F),              
                       
c1_20%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    first_pref = sum(preferencia_postulante == 1))%>%
  select(rbd, cod_curso, first_pref)%>%
  filter(duplicated(rbd, cod_curso) == F),

c1_20%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    second_pref = sum(preferencia_postulante == 2))%>%
  select(rbd, cod_curso, second_pref)%>%
  filter(duplicated(rbd, cod_curso) == F),

c1_20%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    third_pref = sum(preferencia_postulante == 3))%>%
  select(rbd, cod_curso, third_pref)%>%
  filter(duplicated(rbd, cod_curso) == F)) %>%
  
  reduce(left_join, by = c('rbd', 'cod_curso'))

c1_20 <- data.frame(c1_20%>%
  group_by(mrun)%>%
  mutate(
    alguna_prio = ifelse(prioridad_matriculado == 1 | prioridad_hermano == 1 | prioridad_hijo_funcionario == 1 | prioridad_exalumno == 1, 1,0),
    alguna_prio = max(alguna_prio),
    prio_colegio_origen = max(prioridad_matriculado),
    prio_fam = ifelse(prioridad_hermano == 1 | prioridad_hijo_funcionario == 1, 1,0),
    prio_fam = max(prio_fam)))
```

### Oferta
```{r}
#caso unico para rbd 2018
a1_20 <- a1_20%>%
  mutate(
    unico = duplicated(a1_20$rbd),
    unico = ifelse(unico == FALSE, 1, 0))

mat20 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/Resumen de matrícula por establecimiento/Resumen-matricula-EE-2020/Resumen_Matricula_EE_Oficial_2020.csv")

a1_20 <- left_join(a1_20, mat20 %>%
  select(RBD, COD_DEPE2, RURAL_RBD, COD_REG_RBD, MAT_TOTAL)%>%
  rename(rbd = RBD, dep = COD_DEPE2, zona = RURAL_RBD, mat_total = MAT_TOTAL, region = COD_REG_RBD), by = 'rbd')

a1_20 <- a1_20 %>%
  mutate(dep = ifelse(dep == 1 | dep == 5, 0,1))

a1_20 <- a1_20%>%
  mutate(
    macro = ifelse(region == 15 | region == 1| region == 2 | region == 3, 0,
                  ifelse(region == 4 | region == 5, 1,
                  ifelse(region == 6 | region == 7 | region == 8 |region == 16, 2,
                  ifelse(region == 9 | region == 10 | region == 14, 3,
                  ifelse(region == 11 | region == 12, 4, 5))))))

dir20 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/1. Datos Abiertos MINEDUC/Directorio Establecimientos/Directorio-oficial-EE-2020/Directorio_Oficial_EE_2020.csv")

a1_20 <- left_join(a1_20, dir20%>%
  select(RBD, PAGO_MATRICULA, PAGO_MENSUAL)%>%
    rename(rbd = RBD), by = 'rbd')

a1_20 <- a1_20%>%
  mutate(PAGO_MATRICULA = ifelse(PAGO_MATRICULA == '$1.000 A $10.000' | PAGO_MATRICULA == '$10.001 A $25.000', 1,
        ifelse(PAGO_MATRICULA == '$25.001 A $50.000' | PAGO_MATRICULA == '$50.001 A $100.000', 2,
        ifelse(PAGO_MATRICULA == 'MAS DE $100.000', 3,
        ifelse(PAGO_MATRICULA == 'GRATUITO', 0, NA)))))

a1_20 <- a1_20%>%
  mutate(PAGO_MENSUAL = ifelse(PAGO_MENSUAL == '$1.000 A $10.000' | PAGO_MENSUAL == '$10.001 A $25.000', 1,
    ifelse(PAGO_MENSUAL == '$25.001 A $50.000' | PAGO_MENSUAL == '$50.001 A $100.000', 2,
    ifelse(PAGO_MENSUAL == 'MAS DE $100.000', 3, 
    ifelse(PAGO_MENSUAL == 'GRATUITO', 0, NA)))))

sep20 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/1. Datos Abiertos MINEDUC/Alumnos SEP por rbd (MINEDUC)/SEP-2020/Preferentes_Prioritarios_y_Beneficiarios_SEP_2020.csv")

a1_20 <- left_join(a1_20, sep20%>%
  select(RBD, N_PRIO)%>%
  rename(rbd = RBD), by = 'rbd')

a1_20 <- a1_20%>%
  mutate(
    N_PRIO = ifelse(is.na(N_PRIO) == T, 0, N_PRIO),
    prop_prio_mattotal = N_PRIO/mat_total,
    prop_prio_mattotal = ifelse(prop_prio_mattotal <= .25, 0,
                            ifelse(prop_prio_mattotal >= .2500001 & prop_prio_mattotal <= .5, 1,2)))

CDB2019 <- read_excel("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/2. Agencia de Calidad de la Educación/Categorías de desempeño/CDB2019.xlsx")

CDM2019 <- read_excel("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/2. Agencia de Calidad de la Educación/Categorías de desempeño/CDM2019.xlsx")

a1_20 <- data.frame(list(a1_20,
  CDB2019%>%
  select(RBD, `Categoría Desempeño 2019`)%>%
  rename(rbd = RBD, CDB_2019 = `Categoría Desempeño 2019`),
  
  CDM2019%>%
  select(RBD, `Categoría Desempeño 2019`)%>%
  rename(rbd = RBD, CDM_2019 = `Categoría Desempeño 2019`))%>%
  
    reduce(left_join, by = c('rbd')))

a1_20 <- a1_20%>%
  mutate(
    CDB_2019 = ifelse(CDB_2019 == 'ALTO', 3,
                      ifelse(CDB_2019 == 'INSUFICIENTE', 0,
                             ifelse(CDB_2019 == 'MEDIO', 2,
                                    ifelse(CDB_2019 == 'MEDIO-BAJO' | CDB_2019 == 'MEDIO-BAJO (NUEVO)', 1, NA)))),
    CDM_2019 = ifelse(CDM_2019 == 'ALTO', 3,
                      ifelse(CDM_2019 == 'INSUFICIENTE', 0,
                             ifelse(CDM_2019 == 'MEDIO', 2,
                                    ifelse(CDM_2019 == 'MEDIO-BAJO' | CDM_2019 == 'MEDIO-BAJO (NUEVO)', 1, NA)))))

a1_20 <- data.frame(a1_20%>%
  group_by(rbd)%>%
  mutate(
    CDB_2019 = ifelse(is.na(CDB_2019), -1, CDB_2019),
    CDM_2019 = ifelse(is.na(CDM_2019), -1, CDM_2019),
    CDG = max(CDB_2019, CDM_2019),
    CDG = ifelse(CDG == -1, NA, CDG)))

a1_20 <- a1_20%>%
  mutate(
    ciclo_educativo = ifelse(cod_nivel < 1, 0,
    ifelse(cod_nivel >= 1 & cod_nivel < 9,1,2)))

a1_20 <- left_join(a1_20, c1_20%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    demanda_cod_curso = n())%>%
  select(rbd, cod_curso, demanda_cod_curso)%>%
  filter(duplicated(rbd, cod_curso) == F))

a1_20 <- a1_20%>%
  mutate(demanda_cod_curso = ifelse(is.na(demanda_cod_curso) == T, 0, demanda_cod_curso))

a1_20 <- left_join(a1_20, c1_20%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    first_pref = sum(preferencia_postulante == 1))%>%
  select(rbd, cod_curso, first_pref)%>%
  filter(duplicated(rbd, cod_curso) == F), by = c('rbd', 'cod_curso'))

a1_20 <- a1_20%>%
  mutate(first_pref = ifelse(is.na(first_pref) == T, 0, first_pref))

a1_20 <- a1_20%>%
  mutate(
    col_ps_tipos = ifelse(dep == 0, 0,
              ifelse(dep == 1 & prop_prio_mattotal == 0, 1,
              ifelse(dep == 1 & prop_prio_mattotal == 1, 2,
              ifelse(dep == 1 & prop_prio_mattotal == 2, 3, NA)))))

remove(sep20, mat20, dir20, CDM2019, CDB2019)
```

### Resultados
```{r}
d1_20 <- d1_20%>%
  mutate(rbd_admitido = ifelse(is.na(rbd_admitido) == T, -1, rbd_admitido))

d1_20 <- d1_20%>%
  mutate(rbd = ifelse(is.na(rbd_admitido_post_resp) == T, rbd_admitido, rbd_admitido_post_resp))

d1_20 <- left_join(d1_20, c1_20%>%
                     filter(pos_valida == 1)%>%
            select(mrun, rbd, preferencia_postulante, prioridad_matriculado, prioridad_matriculado:prioridad_exalumno, es_pie), by = c('mrun', 'rbd'))

d1_20 <- d1_20%>%
  mutate(cambia_colegio = ifelse(respuesta_postulante == 2 & rbd_admitido == rbd_admitido_post_resp, 0,
  ifelse(respuesta_postulante == 2 & rbd_admitido != rbd_admitido_post_resp, 1, NA)))

d1_20 <- left_join(d1_20, b1_20%>%
            select(mrun, continuidad), by = 'mrun')

d1_20 <- left_join(d1_20, c1_20%>%
                     filter(prioridad_matriculado==1)%>%
            select(mrun, rbd)%>%
              rename(rbd_origen = rbd), by = 'mrun')

d1_20 <- d1_20%>%
  mutate(rbd_admision = ifelse(continuidad==1, rbd_admitido, NA))

d1_20 <- left_join(d1_20, a1_20%>%
                     filter(unico == 1)%>%
                     select(rbd, con_copago, dep, zona, prop_prio_mattotal,CDG)%>%
            rename(rbd_origen = rbd, con_copago_or = con_copago, dep_or = dep, zona_or = zona, prop_prio_mattotal_or = prop_prio_mattotal, CDG_or = CDG), by = 'rbd_origen')


d1_20 <- left_join(d1_20, a1_20%>%
                     filter(unico == 1)%>%
                     select(rbd, con_copago, dep, zona, prop_prio_mattotal,CDG)%>%
            rename(rbd_admision = rbd, con_copago_ad = con_copago, dep_ad = dep, zona_ad = zona, prop_prio_mattotal_ad = prop_prio_mattotal,CDG_ad = CDG), by = 'rbd_admision')
```

## 2021

### Postulantes
```{r}
b1_21  <- left_join(b1_21, c1_21%>%
  group_by(mrun)%>%
  summarise(continuidad = sum(prioridad_matriculado)), by = 'mrun')

b1_21 <- b1_21%>%
  mutate(
    cod_nivel = ifelse(cod_nivel < 1, 0,
    ifelse(cod_nivel == 1,1,
    ifelse(cod_nivel > 1 & cod_nivel < 9,2,
    ifelse(cod_nivel == 9, 3, 4)))))
```

### Postulaciones
```{r}
c1_21 <- data.frame(c1_21%>%
  arrange(mrun, preferencia_postulante)%>%
  group_by(mrun, rbd)%>%
    mutate(pos_valida = ifelse(duplicated(mrun, rbd) == F, 1,0)))

c1_21 <- list(c1_21,
     
c1_21%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    demanda_cod_curso = n())%>%
  select(rbd, cod_curso, demanda_cod_curso)%>%
  filter(duplicated(rbd, cod_curso) == F),              
                       
c1_21%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    first_pref = sum(preferencia_postulante == 1))%>%
  select(rbd, cod_curso, first_pref)%>%
  filter(duplicated(rbd, cod_curso) == F),

c1_21%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    second_pref = sum(preferencia_postulante == 2))%>%
  select(rbd, cod_curso, second_pref)%>%
  filter(duplicated(rbd, cod_curso) == F),

c1_21%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    third_pref = sum(preferencia_postulante == 3))%>%
  select(rbd, cod_curso, third_pref)%>%
  filter(duplicated(rbd, cod_curso) == F)) %>%
  
  reduce(left_join, by = c('rbd', 'cod_curso'))

c1_21 <- data.frame(c1_21%>%
  group_by(mrun)%>%
  mutate(
    alguna_prio = ifelse(prioridad_matriculado == 1 | prioridad_hermano == 1 | prioridad_hijo_funcionario == 1 | prioridad_exalumno == 1, 1,0),
    alguna_prio = max(alguna_prio),
    prio_colegio_origen = max(prioridad_matriculado),
    prio_fam = ifelse(prioridad_hermano == 1 | prioridad_hijo_funcionario == 1, 1,0),
    prio_fam = max(prio_fam)))
```

### Oferta
```{r}
#caso unico para rbd 2018
a1_21 <- a1_21%>%
  mutate(
    unico = duplicated(a1_21$rbd),
    unico = ifelse(unico == FALSE, 1, 0))

mat21 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/Resumen de matrícula por establecimiento/Resumen-matricula-EE-2021/Resumen_Matricula_EE_Oficial_2021.csv")

a1_21<- left_join(a1_21, mat21 %>%
  select(RBD, COD_DEPE2, RURAL_RBD, COD_REG_RBD, MAT_TOTAL)%>%
  rename(rbd = RBD, dep = COD_DEPE2, zona = RURAL_RBD, mat_total = MAT_TOTAL, region = COD_REG_RBD), by = 'rbd')

a1_21<- a1_21%>%
  mutate(dep = ifelse(dep == 1 | dep == 5, 0,1))

a1_21<- a1_21%>%
  mutate(
    macro = ifelse(region == 15 | region == 1| region == 2 | region == 3, 0,
                  ifelse(region == 4 | region == 5, 1,
                  ifelse(region == 6 | region == 7 | region == 8 |region == 16, 2,
                  ifelse(region == 9 | region == 10 | region == 14, 3,
                  ifelse(region == 11 | region == 12, 4, 5))))))

dir21 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/1. Datos Abiertos MINEDUC/Directorio Establecimientos/Directorio-oficial-EE-2021/Directorio_Oficial_EE_2021.csv")

a1_21<- left_join(a1_21, dir21%>%
  select(RBD, PAGO_MATRICULA, PAGO_MENSUAL)%>%
    rename(rbd = RBD), by = 'rbd')

a1_21<- a1_21%>%
  mutate(PAGO_MATRICULA = ifelse(PAGO_MATRICULA == '$1.000 A $10.000' | PAGO_MATRICULA == '$10.001 A $25.000', 1,
        ifelse(PAGO_MATRICULA == '$25.001 A $50.000' | PAGO_MATRICULA == '$50.001 A $100.000', 2,
        ifelse(PAGO_MATRICULA == 'MAS DE $100.000', 3,
        ifelse(PAGO_MATRICULA == 'GRATUITO', 0, NA)))))

a1_21<- a1_21%>%
  mutate(PAGO_MENSUAL = ifelse(PAGO_MENSUAL == '$1.000 A $10.000' | PAGO_MENSUAL == '$10.001 A $25.000', 1,
    ifelse(PAGO_MENSUAL == '$25.001 A $50.000' | PAGO_MENSUAL == '$50.001 A $100.000', 2,
    ifelse(PAGO_MENSUAL == 'MAS DE $100.000', 3, 
    ifelse(PAGO_MENSUAL == 'GRATUITO', 0, NA)))))

sep21 <- read.csv2("C:/Users/geral/OneDrive - University of Iowa/CIDCIE/1. Bases de Datos/1. Datos Abiertos MINEDUC/Alumnos SEP por rbd (MINEDUC)/SEP-2021/Preferentes_Prioritarios_y_Beneficiarios_SEP_2021.csv")

a1_21<- left_join(a1_21, sep21%>%
  select(RBD, N_PRIO)%>%
  rename(rbd = RBD), by = 'rbd')

a1_21<- a1_21%>%
  mutate(
    N_PRIO = ifelse(is.na(N_PRIO) == T, 0, N_PRIO),
    prop_prio_mattotal = N_PRIO/mat_total,
    prop_prio_mattotal = ifelse(prop_prio_mattotal <= .25, 0,
                            ifelse(prop_prio_mattotal >= .2500001 & prop_prio_mattotal <= .5, 1,2)))

a1_21<- a1_21%>%
  mutate(
    ciclo_educativo = ifelse(cod_nivel < 1, 0,
    ifelse(cod_nivel >= 1 & cod_nivel < 9,1,2)))

a1_21<- left_join(a1_21, c1_21%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    demanda_cod_curso = n())%>%
  select(rbd, cod_curso, demanda_cod_curso)%>%
  filter(duplicated(rbd, cod_curso) == F))

a1_21<- a1_21%>%
  mutate(demanda_cod_curso = ifelse(is.na(demanda_cod_curso) == T, 0, demanda_cod_curso))

a1_21 <- left_join(a1_21, c1_21%>%
  filter(pos_valida == 1, agregada_por_continuidad == 0)%>%
  group_by(rbd, cod_curso)%>%
  mutate(
    first_pref = sum(preferencia_postulante == 1))%>%
  select(rbd, cod_curso, first_pref)%>%
  filter(duplicated(rbd, cod_curso) == F), by = c('rbd', 'cod_curso'))

a1_21 <- a1_21%>%
  mutate(first_pref = ifelse(is.na(first_pref) == T, 0, first_pref))

a1_21 <- a1_21%>%
  mutate(
    col_ps_tipos = ifelse(dep == 0, 0,
              ifelse(dep == 1 & prop_prio_mattotal == 0, 1,
              ifelse(dep == 1 & prop_prio_mattotal == 1, 2,
              ifelse(dep == 1 & prop_prio_mattotal == 2, 3, NA)))))
    
remove(sep21, mat21, dir21)
```

### Resultados
```{r}
d1_21 <- d1_21%>%
  mutate(rbd_admitido = ifelse(is.na(rbd_admitido) == T, -1, rbd_admitido))

d1_21 <- d1_21%>%
  mutate(rbd = ifelse(is.na(rbd_admitido_post_resp) == T, rbd_admitido, rbd_admitido_post_resp))

d1_21 <- left_join(d1_21, c1_21%>%
                     filter(pos_valida == 1)%>%
            select(mrun, rbd, preferencia_postulante, prioridad_matriculado, prioridad_matriculado:prioridad_exalumno, es_pie), by = c('mrun', 'rbd'))

d1_21 <- d1_21%>%
  mutate(cambia_colegio = ifelse(respuesta_postulante == 2 & rbd_admitido == rbd_admitido_post_resp, 0,
  ifelse(respuesta_postulante == 2 & rbd_admitido != rbd_admitido_post_resp, 1, NA)))

d1_21 <- left_join(d1_21, b1_21%>%
            select(mrun, continuidad), by = 'mrun')

d1_21 <- left_join(d1_21, c1_21%>%
                     filter(prioridad_matriculado==1)%>%
            select(mrun, rbd)%>%
              rename(rbd_origen = rbd), by = 'mrun')

d1_21 <- d1_21%>%
  mutate(rbd_admision = ifelse(continuidad==1, rbd_admitido, NA))

d1_21 <- left_join(d1_21, a1_21%>%
                     filter(unico == 1)%>%
                     select(rbd, con_copago, dep, zona, prop_prio_mattotal)%>%
            rename(rbd_origen = rbd, con_copago_or = con_copago, dep_or = dep, zona_or = zona, prop_prio_mattotal_or = prop_prio_mattotal), by = 'rbd_origen')

d1_21 <- left_join(d1_21, a1_21%>%
                     filter(unico == 1)%>%
                     select(rbd, con_copago, dep, zona, prop_prio_mattotal)%>%
            rename(rbd_admision = rbd, con_copago_ad = con_copago, dep_ad = dep, zona_ad = zona, prop_prio_mattotal_ad = prop_prio_mattotal), by = 'rbd_admision')
```

# Tabla 1
```{r}
#2018
a1_18 %>%
  filter(unico == 1)%>%
  count(cod_jor)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_18 %>%
  filter(unico == 1)%>%
  count(con_copago)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_18 %>%
  filter(unico == 1)%>%
  count(dep)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_18 %>%
  filter(unico == 1)%>%
  count(zona)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_18 %>%
  filter(unico == 1)%>%
  count(macro)%>%
  mutate(prop = round(n/sum(n),3) * 100)

#2019
a1_19 %>%
  filter(unico == 1)%>%
  count(cod_jor)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_19 %>%
  filter(unico == 1)%>%
  count(con_copago)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_19 %>%
  filter(unico == 1)%>%
  count(dep)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_19 %>%
  filter(unico == 1)%>%
  count(zona)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_19 %>%
  filter(unico == 1)%>%
  count(macro)%>%
  mutate(prop = round(n/sum(n),3) * 100)

#2020
a1_20 %>%
  filter(unico == 1)%>%
  count(cod_jor)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_20 %>%
  filter(unico == 1)%>%
  count(con_copago)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_20 %>%
  filter(unico == 1)%>%
  count(dep)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_20 %>%
  filter(unico == 1)%>%
  count(zona)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_20 %>%
  filter(unico == 1)%>%
  count(macro)%>%
  mutate(prop = round(n/sum(n),3) * 100)

#2021
a1_21 %>%
  filter(unico == 1)%>%
  count(cod_jor)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_21 %>%
  filter(unico == 1)%>%
  count(con_copago)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_21 %>%
  filter(unico == 1)%>%
  count(dep)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_21 %>%
  filter(unico == 1)%>%
  count(zona)%>%
  mutate(prop = round(n/sum(n),3) * 100)

a1_21 %>%
  filter(unico == 1)%>%
  count(macro)%>%
  mutate(prop = round(n/sum(n),3) * 100)
```

# Tabla 2
```{r}
#2018
b1_18%>%
  count(cod_nivel)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_18%>%
  count(es_mujer)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_18%>%
  count(prioritario)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_18%>%
  count(alto_rendimiento)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_18%>%
  count(continuidad)%>%
  mutate(prop = round(n/sum(n),3)*100)

#2019
b1_19%>%
  count(cod_nivel)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_19%>%
  count(es_mujer)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_19%>%
  count(prioritario)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_19%>%
  count(alto_rendimiento)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_19%>%
  count(continuidad)%>%
  mutate(prop = round(n/sum(n),3)*100)

#2020
b1_20%>%
  count(cod_nivel)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_20%>%
  count(es_mujer)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_20%>%
  count(prioritario)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_20%>%
  count(alto_rendimiento)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_20%>%
  count(continuidad)%>%
  mutate(prop = round(n/sum(n),3)*100)

#2021
b1_21%>%
  count(cod_nivel)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_21%>%
  count(es_mujer)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_21%>%
  count(prioritario)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_21%>%
  count(alto_rendimiento)%>%
  mutate(prop = round(n/sum(n),3)*100)

b1_21%>%
  count(continuidad)%>%
  mutate(prop = round(n/sum(n),3)*100)
```

# Tabla 3
```{r}
#2018
dim(c1_18)

c1_18%>%
  count(pos_valida) #0

c1_18%>%
  count(agregada_por_continuidad) #1

c1_18%>%
  filter(agregada_por_continuidad == 0, pos_valida == 1)%>%
  nrow()

a1_18%>%
  group_by(ciclo_educativo)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_18%>%
  group_by(con_copago)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_18%>%
  group_by(dep)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_18%>%
  group_by(prop_prio_mattotal)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_18%>%
  group_by(CDG)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  drop_na()%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_18%>%
  group_by(gse_rbd)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  filter(gse_rbd != -1)%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_18%>%
  group_by(ins_mat_rbd)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  filter(ins_mat_rbd != -1)%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_18%>%
  group_by(ins_lec_rbd)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  filter(ins_lec_rbd != -1)%>%
  mutate(prop = round(s/sum(s),3)*100)

#2019
dim(c1_19)

c1_19%>%
  count(pos_valida) #0

c1_19%>%
  count(agregada_por_continuidad) #1

c1_19%>%
  filter(agregada_por_continuidad == 0, pos_valida == 1)%>%
  nrow()

a1_19%>%
  group_by(ciclo_educativo)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_19%>%
  group_by(con_copago)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_19%>%
  group_by(dep)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_19%>%
  group_by(prop_prio_mattotal)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_19%>%
  group_by(CDG)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  drop_na()%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_19%>%
  group_by(gse_rbd)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  filter(gse_rbd != -1)%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_19%>%
  group_by(ins_mat_rbd)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  filter(ins_mat_rbd != -1)%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_19%>%
  group_by(ins_lec_rbd)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  filter(ins_lec_rbd != -1)%>%
  mutate(prop = round(s/sum(s),3)*100)

#2020
dim(c1_20)

c1_20%>%
  count(pos_valida) #0

c1_20%>%
  count(agregada_por_continuidad) #1

c1_20%>%
  filter(agregada_por_continuidad == 0, pos_valida == 1)%>%
  nrow()

a1_20%>%
  group_by(ciclo_educativo)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_20%>%
  group_by(con_copago)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_20%>%
  group_by(dep)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_20%>%
  group_by(prop_prio_mattotal)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  na.omit()%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_20%>%
  group_by(CDG)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  drop_na()%>%
  mutate(prop = round(s/sum(s),3)*100)

#2021
dim(c1_21)

c1_21%>%
  count(pos_valida) #0

c1_21%>%
  count(agregada_por_continuidad) #1

c1_21%>%
  filter(agregada_por_continuidad == 0, pos_valida == 1)%>%
  nrow()

a1_21%>%
  group_by(ciclo_educativo)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_21%>%
  group_by(con_copago)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_21%>%
  group_by(dep)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_21%>%
  group_by(prop_prio_mattotal)%>%
  summarise(s = sum(demanda_cod_curso))%>%
  na.omit()%>%
  mutate(prop = round(s/sum(s),3)*100)
```

# Tabla 4
```{r}
# 2018
a1_18%>%
  group_by(rbd)%>%
  mutate(pos_rbd = sum(demanda_cod_curso),
         vacantes_rbd = sum(vacantes),
         first_rbd = sum(first_pref))%>%
  filter(unico == 1)%>%
  ungroup(rbd)%>%
  group_by(col_ps_tipos)%>%
  summarise(colegios = n(),
            vacancies = sum(vacantes_rbd),
            postulaciones_rbd = sum(pos_rbd),
            f_pref = sum(first_rbd),
            pos_promedio = postulaciones_rbd/colegios,
            ratio_pos_vac = postulaciones_rbd/vacancies,
            vac_ocup = f_pref/vacancies)

a1_18%>%
  group_by(rbd)%>%
  mutate(pos_rbd = sum(demanda_cod_curso),
         vacantes_rbd = sum(vacantes),
         first_rbd = sum(first_pref))%>%
  filter(unico == 1)%>%
  ungroup(rbd)%>%
  group_by(con_copago)%>%
  summarise(colegios = n(),
            vacancies = sum(vacantes_rbd),
            postulaciones_rbd = sum(pos_rbd),
            f_pref = sum(first_rbd),
            pos_promedio = postulaciones_rbd/colegios,
            ratio_pos_vac = postulaciones_rbd/vacancies,
            vac_ocup = f_pref/vacancies)

a1_18%>%
  group_by(rbd)%>%
  mutate(pos_rbd = sum(demanda_cod_curso),
         vacantes_rbd = sum(vacantes),
         first_rbd = sum(first_pref))%>%
  filter(unico == 1)%>%
  ungroup(rbd)%>%
  group_by(prop_prio_mattotal)%>%
  filter(is.na(prop_prio_mattotal) == F)%>%
  summarise(colegios = n(),
            vacancies = sum(vacantes_rbd),
            postulaciones_rbd = sum(pos_rbd),
            f_pref = sum(first_rbd),
            pos_promedio = postulaciones_rbd/colegios,
            ratio_pos_vac = postulaciones_rbd/vacancies,
            vac_ocup = f_pref/vacancies)

#2019
a1_19%>%
  group_by(rbd)%>%
  mutate(pos_rbd = sum(demanda_cod_curso),
         vacantes_rbd = sum(vacantes),
         first_rbd = sum(first_pref))%>%
  filter(unico == 1)%>%
  ungroup(rbd)%>%
  group_by(col_ps_tipos)%>%
  summarise(colegios = n(),
            vacancies = sum(vacantes_rbd),
            postulaciones_rbd = sum(pos_rbd),
            f_pref = sum(first_rbd),
            pos_promedio = postulaciones_rbd/colegios,
            ratio_pos_vac = postulaciones_rbd/vacancies,
            vac_ocup = f_pref/vacancies)

a1_19%>%
  group_by(rbd)%>%
  mutate(pos_rbd = sum(demanda_cod_curso),
         vacantes_rbd = sum(vacantes),
         first_rbd = sum(first_pref))%>%
  filter(unico == 1)%>%
  ungroup(rbd)%>%
  group_by(con_copago)%>%
  summarise(colegios = n(),
            vacancies = sum(vacantes_rbd),
            postulaciones_rbd = sum(pos_rbd),
            f_pref = sum(first_rbd),
            pos_promedio = postulaciones_rbd/colegios,
            ratio_pos_vac = postulaciones_rbd/vacancies,
            vac_ocup = f_pref/vacancies)

a1_19%>%
  group_by(rbd)%>%
  mutate(pos_rbd = sum(demanda_cod_curso),
         vacantes_rbd = sum(vacantes),
         first_rbd = sum(first_pref))%>%
  filter(unico == 1)%>%
  ungroup(rbd)%>%
  group_by(prop_prio_mattotal)%>%
  filter(is.na(prop_prio_mattotal) == F)%>%
  summarise(colegios = n(),
            vacancies = sum(vacantes_rbd),
            postulaciones_rbd = sum(pos_rbd),
            f_pref = sum(first_rbd),
            pos_promedio = postulaciones_rbd/colegios,
            ratio_pos_vac = postulaciones_rbd/vacancies,
            vac_ocup = f_pref/vacancies)
#2020
a1_20%>%
  group_by(rbd)%>%
  mutate(pos_rbd = sum(demanda_cod_curso),
         vacantes_rbd = sum(vacantes),
         first_rbd = sum(first_pref))%>%
  filter(unico == 1)%>%
  ungroup(rbd)%>%
  group_by(col_ps_tipos)%>%
  summarise(colegios = n(),
            vacancies = sum(vacantes_rbd),
            postulaciones_rbd = sum(pos_rbd),
            f_pref = sum(first_rbd),
            pos_promedio = postulaciones_rbd/colegios,
            ratio_pos_vac = postulaciones_rbd/vacancies,
            vac_ocup = f_pref/vacancies)%>%
  na.omit()

a1_20%>%
  group_by(rbd)%>%
  mutate(pos_rbd = sum(demanda_cod_curso),
         vacantes_rbd = sum(vacantes),
         first_rbd = sum(first_pref))%>%
  filter(unico == 1)%>%
  ungroup(rbd)%>%
  group_by(con_copago)%>%
  summarise(colegios = n(),
            vacancies = sum(vacantes_rbd),
            postulaciones_rbd = sum(pos_rbd),
            f_pref = sum(first_rbd),
            pos_promedio = postulaciones_rbd/colegios,
            ratio_pos_vac = postulaciones_rbd/vacancies,
            vac_ocup = f_pref/vacancies)

a1_20%>%
  group_by(rbd)%>%
  mutate(pos_rbd = sum(demanda_cod_curso),
         vacantes_rbd = sum(vacantes),
         first_rbd = sum(first_pref))%>%
  filter(unico == 1)%>%
  ungroup(rbd)%>%
  group_by(prop_prio_mattotal)%>%
  filter(is.na(prop_prio_mattotal) == F)%>%
  summarise(colegios = n(),
            vacancies = sum(vacantes_rbd),
            postulaciones_rbd = sum(pos_rbd),
            f_pref = sum(first_rbd),
            pos_promedio = postulaciones_rbd/colegios,
            ratio_pos_vac = postulaciones_rbd/vacancies,
            vac_ocup = f_pref/vacancies)

#2021
a1_21%>%
  group_by(rbd)%>%
  mutate(pos_rbd = sum(demanda_cod_curso),
         vacantes_rbd = sum(vacantes),
         first_rbd = sum(first_pref))%>%
  filter(unico == 1)%>%
  ungroup(rbd)%>%
  group_by(col_ps_tipos)%>%
  summarise(colegios = n(),
            vacancies = sum(vacantes_rbd),
            postulaciones_rbd = sum(pos_rbd),
            f_pref = sum(first_rbd),
            pos_promedio = postulaciones_rbd/colegios,
            ratio_pos_vac = postulaciones_rbd/vacancies,
            vac_ocup = f_pref/vacancies)%>%
  na.omit()

a1_21%>%
  group_by(rbd)%>%
  mutate(pos_rbd = sum(demanda_cod_curso),
         vacantes_rbd = sum(vacantes),
         first_rbd = sum(first_pref))%>%
  filter(unico == 1)%>%
  ungroup(rbd)%>%
  group_by(con_copago)%>%
  summarise(colegios = n(),
            vacancies = sum(vacantes_rbd),
            postulaciones_rbd = sum(pos_rbd),
            f_pref = sum(first_rbd),
            pos_promedio = postulaciones_rbd/colegios,
            ratio_pos_vac = postulaciones_rbd/vacancies,
            vac_ocup = f_pref/vacancies)

a1_21%>%
  group_by(rbd)%>%
  mutate(pos_rbd = sum(demanda_cod_curso),
         vacantes_rbd = sum(vacantes),
         first_rbd = sum(first_pref))%>%
  filter(unico == 1)%>%
  ungroup(rbd)%>%
  group_by(prop_prio_mattotal)%>%
  filter(is.na(prop_prio_mattotal) == F)%>%
  summarise(colegios = n(),
            vacancies = sum(vacantes_rbd),
            postulaciones_rbd = sum(pos_rbd),
            f_pref = sum(first_rbd),
            pos_promedio = postulaciones_rbd/colegios,
            ratio_pos_vac = postulaciones_rbd/vacancies,
            vac_ocup = f_pref/vacancies)
```

# Tabla 5
```{r}
#2018
nrow(d1_18)

d1_18%>%
  filter(rbd_admitido > 0)%>%
  nrow()

d1_18%>%
  filter(rbd_admitido == -1)%>%
  nrow()

d1_18%>%
  filter(respuesta_postulante != 6)%>%
  count(respuesta_postulante)%>%
  mutate(
    n2 = ifelse(respuesta_postulante == 1 | respuesta_postulante == 5,n, NA),
    n2 = sum(n2, na.rm = T),
    n2 = ifelse(respuesta_postulante == 1 | respuesta_postulante == 5, n2, n))%>%
  filter(respuesta_postulante != 5)%>%
    mutate(prop = round(n2/sum(n2),3)*100)

d1_18%>%
  filter(respuesta_postulante == 2)%>%
  count(respuesta_postulante_post_lista_espera)

d1_18%>%
  count(cambia_colegio)%>%
  na.omit()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_18%>%
  filter(respuesta_postulante == 6)%>%
  count(respuesta_postulante_post_lista_espera)%>%
  mutate(
    n2 = ifelse(respuesta_postulante_post_lista_espera == 1 | respuesta_postulante_post_lista_espera == 5, n, NA),
    n2 = sum(n2, na.rm = T),
    n2 = ifelse(respuesta_postulante_post_lista_espera == 1 | respuesta_postulante_post_lista_espera == 5, n2, n))%>%
  filter(respuesta_postulante_post_lista_espera != 5)

#2019
nrow(d1_19)

d1_19%>%
  filter(rbd_admitido > 0)%>%
  nrow()

d1_19%>%
  filter(rbd_admitido == -1)%>%
  nrow()

d1_19%>%
  filter(respuesta_postulante != 6)%>%
  count(respuesta_postulante)%>%
  mutate(
    n2 = ifelse(respuesta_postulante == 1 | respuesta_postulante == 5,n, NA),
    n2 = sum(n2, na.rm = T),
    n2 = ifelse(respuesta_postulante == 1 | respuesta_postulante == 5, n2, n))%>%
  filter(respuesta_postulante != 5)%>%
    mutate(prop = round(n2/sum(n2),3)*100)

d1_19%>%
  filter(respuesta_postulante == 2)%>%
  count(respuesta_postulante_post_lista_espera)

d1_19%>%
  count(cambia_colegio)%>%
  na.omit()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_19%>%
  filter(respuesta_postulante == 6)%>%
  count(respuesta_postulante_post_lista_espera)%>%
  mutate(
    n2 = ifelse(respuesta_postulante_post_lista_espera == 1 | respuesta_postulante_post_lista_espera == 5, n, NA),
    n2 = sum(n2, na.rm = T),
    n2 = ifelse(respuesta_postulante_post_lista_espera == 1 | respuesta_postulante_post_lista_espera == 5, n2, n))%>%
  filter(respuesta_postulante_post_lista_espera != 5)%>%
  mutate(prop = round(n2/sum(n2),3)*100)

#2020
nrow(d1_20)

d1_20%>%
  filter(rbd_admitido > 0)%>%
  nrow()

d1_20%>%
  filter(rbd_admitido == -1)%>%
  nrow()

d1_20%>%
  filter(respuesta_postulante != 6)%>%
  count(respuesta_postulante)%>%
  mutate(
    n2 = ifelse(respuesta_postulante == 1 | respuesta_postulante == 5,n, NA),
    n2 = sum(n2, na.rm = T),
    n2 = ifelse(respuesta_postulante == 1 | respuesta_postulante == 5, n2, n))%>%
  filter(respuesta_postulante != 5)%>%
    mutate(prop = round(n2/sum(n2),3)*100)

d1_20%>%
  filter(respuesta_postulante == 2)%>%
  count(respuesta_postulante_post_lista_espera)

d1_20%>%
  count(cambia_colegio)%>%
  na.omit()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_20%>%
  filter(respuesta_postulante == 6)%>%
  count(respuesta_postulante_post_lista_espera)%>%
  mutate(
    n2 = ifelse(respuesta_postulante_post_lista_espera == 1 | respuesta_postulante_post_lista_espera == 5, n, NA),
    n2 = sum(n2, na.rm = T),
    n2 = ifelse(respuesta_postulante_post_lista_espera == 1 | respuesta_postulante_post_lista_espera == 5, n2, n))%>%
  filter(respuesta_postulante_post_lista_espera != 5)%>%
  mutate(prop = round(n2/sum(n2),3)*100)

#2021
nrow(d1_21)

d1_21%>%
  filter(rbd_admitido > 0)%>%
  nrow()

d1_21%>%
  filter(rbd_admitido == -1)%>%
  nrow()

d1_21%>%
  filter(respuesta_postulante != 6)%>%
  count(respuesta_postulante)%>%
  mutate(
    n2 = ifelse(respuesta_postulante == 1 | respuesta_postulante == 5,n, NA),
    n2 = sum(n2, na.rm = T),
    n2 = ifelse(respuesta_postulante == 1 | respuesta_postulante == 5, n2, n))%>%
  filter(respuesta_postulante != 5)%>%
    mutate(prop = round(n2/sum(n2),3)*100)

d1_21%>%
  filter(respuesta_postulante == 2)%>%
  count(respuesta_postulante_post_lista_espera)

d1_21%>%
  count(cambia_colegio)%>%
  na.omit()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_21%>%
  filter(respuesta_postulante == 6)%>%
  count(respuesta_postulante_post_lista_espera)%>%
  mutate(
    n2 = ifelse(respuesta_postulante_post_lista_espera == 1 | respuesta_postulante_post_lista_espera == 5, n, NA),
    n2 = sum(n2, na.rm = T),
    n2 = ifelse(respuesta_postulante_post_lista_espera == 1 | respuesta_postulante_post_lista_espera == 5, n2, n))%>%
  filter(respuesta_postulante_post_lista_espera != 5)%>%
  mutate(prop = round(n2/sum(n2),3)*100)
```

# Tabla 6
```{r}
#2018
d1_18%>%
  count(preferencia_postulante)%>%
  mutate(n2 = ifelse(preferencia_postulante > 3, n, NA),
         n2 = sum(n2, na.rm = T),
         n2 = ifelse(preferencia_postulante > 3, n2, n))%>%
  filter(preferencia_postulante < 5)%>%
  mutate(prop = round(n2/sum(n2),3)*100)

#2019
d1_19%>%
  count(preferencia_postulante)%>%
  mutate(n2 = ifelse(preferencia_postulante > 3, n, NA),
         n2 = sum(n2, na.rm = T),
         n2 = ifelse(preferencia_postulante > 3, n2, n))%>%
  filter(preferencia_postulante < 5)%>%
  mutate(prop = round(n2/sum(n2),3)*100)

#2020
d1_20%>%
  count(preferencia_postulante)%>%
  mutate(n2 = ifelse(preferencia_postulante > 3, n, NA),
         n2 = sum(n2, na.rm = T),
         n2 = ifelse(preferencia_postulante > 3, n2, n))%>%
  filter(preferencia_postulante < 5)%>%
  mutate(prop = round(n2/sum(n2),3)*100)

#2021
d1_21%>%
  count(preferencia_postulante)%>%
  mutate(n2 = ifelse(preferencia_postulante > 3, n, NA),
         n2 = sum(n2, na.rm = T),
         n2 = ifelse(preferencia_postulante > 3, n2, n))%>%
  filter(preferencia_postulante < 5)%>%
  mutate(prop = round(n2/sum(n2),3)*100)
```

# Tabla 7
```{r}
d1_18%>%
  count(dep_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_18%>%
  count(dep_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_18%>%
  count(con_copago_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_18%>%
  count(con_copago_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_18%>%
  count(zona_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_18%>%
  count(zona_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_18%>%
  count(CDG_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_18%>%
  count(CDG_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_18%>%
  count(prop_prio_mattotal_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_18%>%
  count(prop_prio_mattotal_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

#2019
d1_19%>%
  count(dep_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_19%>%
  count(dep_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_19%>%
  count(con_copago_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_19%>%
  count(con_copago_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_19%>%
  count(zona_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_19%>%
  count(zona_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_19%>%
  count(CDG_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_19%>%
  count(CDG_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_19%>%
  count(prop_prio_mattotal_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_19%>%
  count(prop_prio_mattotal_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

#2020
d1_20%>%
  count(dep_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_20%>%
  count(dep_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_20%>%
  count(con_copago_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_20%>%
  count(con_copago_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_20%>%
  count(zona_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_20%>%
  count(zona_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_20%>%
  count(CDG_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_20%>%
  count(CDG_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_20%>%
  count(prop_prio_mattotal_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_20%>%
  count(prop_prio_mattotal_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

#2021
d1_21%>%
  count(dep_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_21%>%
  count(dep_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_21%>%
  count(con_copago_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_21%>%
  count(con_copago_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_21%>%
  count(zona_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_21%>%
  count(zona_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_21%>%
  count(prop_prio_mattotal_or)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)

d1_21%>%
  count(prop_prio_mattotal_ad)%>%
  drop_na()%>%
  mutate(prop = round(n/sum(n),3)*100)
```

# Primeras preferencias
```{r}
a1_18%>%
  group_by(con_copago)%>%
  summarise(s = sum(first_pref))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_18%>%
  group_by(dep)%>%
  summarise(s = sum(first_pref))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_18%>%
  group_by(prop_prio_mattotal)%>%
  summarise(s = sum(first_pref))%>%
  na.omit()%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_18%>%
  group_by(CDG)%>%
  summarise(s = sum(first_pref))%>%
  drop_na()%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_18%>%
  group_by(gse_rbd)%>%
  summarise(s = sum(first_pref))%>%
  filter(gse_rbd != -1)%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_18%>%
  group_by(ins_mat_rbd)%>%
  summarise(s = sum(first_pref))%>%
  filter(ins_mat_rbd != -1)%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_18%>%
  group_by(ins_lec_rbd)%>%
  summarise(s = sum(first_pref))%>%
  filter(ins_lec_rbd != -1)%>%
  mutate(prop = round(s/sum(s),3)*100)

#2019
a1_19%>%
  group_by(con_copago)%>%
  summarise(s = sum(first_pref))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_19%>%
  group_by(dep)%>%
  summarise(s = sum(first_pref))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_19%>%
  group_by(prop_prio_mattotal)%>%
  summarise(s = sum(first_pref))%>%
  na.omit()%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_19%>%
  group_by(CDG)%>%
  summarise(s = sum(first_pref))%>%
  drop_na()%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_19%>%
  group_by(gse_rbd)%>%
  summarise(s = sum(first_pref))%>%
  filter(gse_rbd != -1)%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_19%>%
  group_by(ins_mat_rbd)%>%
  summarise(s = sum(first_pref))%>%
  filter(ins_mat_rbd != -1)%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_19%>%
  group_by(ins_lec_rbd)%>%
  summarise(s = sum(first_pref))%>%
  filter(ins_lec_rbd != -1)%>%
  mutate(prop = round(s/sum(s),3)*100)

#2020
a1_20%>%
  group_by(con_copago)%>%
  summarise(s = sum(first_pref))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_20%>%
  group_by(dep)%>%
  summarise(s = sum(first_pref))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_20%>%
  group_by(prop_prio_mattotal)%>%
  summarise(s = sum(first_pref))%>%
  na.omit()%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_20%>%
  group_by(CDG)%>%
  summarise(s = sum(first_pref))%>%
  drop_na()%>%
  mutate(prop = round(s/sum(s),3)*100)

#2021
a1_21%>%
  group_by(con_copago)%>%
  summarise(s = sum(first_pref))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_21%>%
  group_by(dep)%>%
  summarise(s = sum(first_pref))%>%
  mutate(prop = round(s/sum(s),3)*100)

a1_21%>%
  group_by(prop_prio_mattotal)%>%
  summarise(s = sum(first_pref))%>%
  na.omit()%>%
  mutate(prop = round(s/sum(s),3)*100)
```
